function save_game(){
    global.room_save = room_get_name(room)
    ini_open("config.ini")
    ini_write_string("config","lang",global.lang)
    ini_write_real("config","time",global.time)
    ini_write_string("config","room",global.room_save)
    ini_write_string("config","name",global.name)
    ini_write_real("config","lv",global.lv)
    ini_write_real("config","att",global.att)
    ini_write_real("config","def",global.def)
    ini_write_real("config","attack",global.attack)
    ini_write_real("config","defense",global.defense)
    ini_write_real("config","exp",global.exp)
    ini_write_real("config","gold",global.gold)
    ini_write_string("config","weapon",global.weapon)
    ini_write_string("config","armor",global.armor)
    ini_close()
}
